name: base_ecom_appsure
description: A new Flutter package project.
homepage:
version: 0.0.1

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: '>=3.16.9'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  hive: ^2.2.3
  path_provider: ^2.1.2
  flutter_riverpod: ^2.4.9
  get_it: ^7.6.7
  dio: ^5.4.0
  retrofit: ^4.0.1
  firebase_analytics: ^10.8.1
  iconsax: ^0.0.8
  add_to_cart_animation: ^2.0.3
  async_queue: ^2.0.0
  gap: ^3.0.1
  rules: ^2.0.0
  webview_flutter: ^4.4.4
  flutter_svg: ^2.0.7
  url_launcher: ^6.2.4
  infinite_scroll_pagination: ^4.0.0
  auto_size_text: ^3.0.0
  cached_network_image: ^3.3.1
  flutter_screenutil: ^5.9.0
  shimmer: ^3.0.0
  font_awesome_flutter: ^10.7.0
  timer_builder: ^2.0.0
  dart_ipify: ^1.1.1
  flutter_rating_bar: ^4.0.1
  intl: ^0.18.1
  lottie: ^3.0.0
  carousel_slider: ^4.2.1
  geocoding: ^2.1.0
  geolocator: ^10.1.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  retrofit_generator: ^8.0.6

flutter:
  assets:
    - assets/svgs/
    - assets/lotties/
